title: 개발자 Kei의 공부일기
description: IT개발을 하면서 공부한 내용을 공유하는 홈페이지

url: https://kshyun87.github.io
baseurl: ""
paginate_path: "/page:num/"
permalink: /:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contact
   url: /contact

social:
   github: kshyun87
   email: kshyun87@gmail.com

google_analytics: "UA-86884796-2"
